name: Keep Render Service Alive

on:
  schedule:
    - cron: '*/12 * * * *'
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service with curl
        id: curl_ping
        run: |
          echo "Pinging https://whatsapp-bot-g7sk.onrender.com ..."
          if curl -sSf --max-time 20 https://whatsapp-bot-g7sk.onrender.com > /dev/null; then
            echo "Ping successful via curl."
          else
            echo "Curl ping failed. Attempting backup with wget..."
            if wget -q --timeout=20 --spider https://whatsapp-bot-g7sk.onrender.com; then
              echo "Ping successful via wget."
            else
              echo "Both curl and wget failed to reach the service."
            fi
          fi
        continue-on-error: true